franchise_title = function(team) {
  # this function takes a franchise abbreviation and returns the respected title. 
  switch (team,
          'ANA' = 'Los Angeles Angels', 
          'ARI' = 'Arizona Diamondbacks',
          'ATL' = 'Atlanta Braves', 
          'BAL' = 'Baltimore Orioles',
          'BOS' = 'Boston Red Sox',
          'CHC' = 'Chicago Cubs',
          'CHW' = 'Chicago White Sox', 
          'CIN' = 'Cincinnati Reds',
          'CLE' = 'Cleveland Indians',
          'COL' = 'Colorado Rockies', 
          'DET' = 'Detroit Tigers',
          'DET' = 'Detroit Tigers', 
          'FLA' = 'Miami Marlins', 
          'HOU' = 'Houston Astros',
          'KCR' = 'Kansas City Royals',
          'LAD' = 'Los Angeles Dodgers',
          'MIL' = 'Milwaukee Brewers', 
          'MIN' = 'Minnesota Twins',
          'NYM' = 'New York Mets', 
          'NYY' = 'New York Yankees', 
          'OAK' = 'Oakland Athletics',
          'PHI' = 'Philadelphia Phillies',
          'PIT' = 'Pittsburgh Pirates',
          'SDP' = 'San Diego Padres', 
          'SEA' = 'Seattle Mariners',
          'SFG' = 'San Francisco Giants',
          'STL' = 'St. Louis Cardinals',
          'TBD' = 'Tampa Bay Rays', 
          'TEX' = 'Texas Rangers',
          'TOR' = 'Toronto Blue Jays',
          'WSN' = 'Washington Nationals'
  )
}